[options]
; This is the password that allows database operations:
; admin_passwd = admin
db_host = localhost
db_port = 5433
db_user = odoo10
db_password = odoo10
dbfilter = cristo_ind_live_sep11
xmlrpc = True
xmlrpc_port = 8069
addons_path = D:\workspace\odoo\odoo-10.0\addons,D:\workspace\CristO-1.0.0\source-v10\extra_addons


